name: "school_guide"

description: A new Flutter project.

publish_to: "none"
version: 0.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^1.0.4

  # flutter_staggered_grid_view: ^0.6.2
  firebase_core: ^1.21.1
  cloud_firestore: ^3.4.6
  carousel_slider: ^4.1.1
  get: ^4.6.5
  url_launcher: ^6.1.6
  intl: ^0.17.0
  timeago: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/

  fonts:
    - family: quicksand
      fonts:
        - asset: assets/fonts/quicksand.ttf
    - family: leguespartan
      fonts:
        - asset: assets/fonts/leguespartan.ttf
    - family: amsterdam
      fonts:
        - asset: assets/fonts/amsterdam.ttf
