name: "school_guide"

description: A new Flutter project.

publish_to: "none"
version: 0.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^1.0.4

  # flutter_staggered_grid_view: ^0.6.2
  # firebase_core: ^1.21.1
  cloud_firestore: ^3.4.6
  carousel_slider: ^4.1.1
  get: ^4.6.5
  url_launcher: ^6.1.6
  intl: ^0.17.0
  timeago: ^3.3.0
  image: ^3.2.2
  cached_network_image: ^3.2.2
  shimmer: ^2.0.0
  youtube_player_flutter: ^8.1.1
  flutter_html: ^3.0.0-alpha.6
  firebase_core: ^1.24.0
  firebase_core_platform_interface: 4.5.1
  scroll_to_index: ^3.0.1
  share_plus: ^6.3.0
  screenshot: ^1.2.3
  http: ^0.13.5
  font_awesome_flutter: ^10.2.1
  firebase_storage: ^10.3.11
  scrollable_positioned_list: ^0.3.5
  # liking
  device_info_plus: ^8.0.0
  shared_preferences: ^2.0.15
  # location
  geolocator: ^9.0.2
  google_maps_flutter: ^2.2.1
  permission_handler: ^10.2.0
  flutter_polyline_points: ^1.0.0
  flutter_cache_manager: ^3.3.0
  double_back_to_close: ^2.0.0
  location: ^4.4.0
  app_settings: ^4.1.8
  video_player: ^2.4.8
  progress_indicators: ^1.0.0
  device_uuid: ^0.0.4
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/

  fonts:
    - family: quicksand
      fonts:
        - asset: assets/fonts/quicksand.ttf
    - family: leguespartan
      fonts:
        - asset: assets/fonts/leguespartan.ttf
    - family: amsterdam
      fonts:
        - asset: assets/fonts/amsterdam.ttf

    - family: richard
      fonts:
        - asset: assets/fonts/richard_signatera.otf
